.gitignore
test/json_parser.test.js
test/mock_parsed_audits/sampleScheduleOutput.json

Added sample tests for json_parser.js.
Note that official tests cannot be added until previous PR is merged, and then json_parser is converted to use module.exports so that functions can be loaded in json_parser.test.js.
Also note that the tests added here do not yet account for the 'name' field in course objects, which will be changed (post merge). 
Also note that a few fields are different in this older version of the code, and so a few property tests were left commented out.
JSON input files have not yet been added to the repository, but will be expected under directory './test/mock_parsed_audits/'
Upon completion of module.exports integration into json_parser.js, the tests can be updated and sampleScheduleOutput.json can be removed.

Schedule testing

---

backend/src/types.ts

This PR is for moving all the old types in types.ts to the bottom of the file.
Perhaps in the future, we should put the types in different files to modulate our types.

moved old types to the bottom

---

backend/package.json
backend/src/plan_parser.ts
backend/test/plan_parser.test.js
yarn.lock

Added plan-of-study parser. 
Right now I've tested it on all of the CAMD Art+Design majors, as well as some randomly picked majors from other colleges. Could potentially test it on more, would just require pasting in more links to the test suite. Fairly simple to do, I wrote a test function that only requires links.
Notable edge cases:
* some plans only have 3 terms/year
* some plans have 5 terms/year
* some plans label their Co-op terms with a number
* sometimes classes don't have credit numbers.
* some electives have numbers in their name
There are probably more edge cases. Please wait for me to test all of the CS majors at the very minimum.

added plan-of-study parser

---

frontend/src/Onboarding/MajorScreen.tsx
frontend/src/components/SemesterBlock.tsx
frontend/src/home/Home.tsx
frontend/src/state/actions/scheduleActions.ts
frontend/src/state/actions/userActions.ts
frontend/src/state/reducers/scheduleReducer.ts
frontend/src/state/reducers/userReducer.ts
frontend/src/utils/schedule-helpers.ts

This PR modifies the plan of study question to only modify the schedule's coop cycle. This way users aren't flooded with a full schedule once they choose their coop cycle. 
Also there is a button for adding all of the courses from the plan they chose. With a clear schedule option too!

Change plan of study to truly just "coop cycle"

---

.github/workflows/main.yml

Checks validity of docker builds as part of CI so we don’t inadvertently merge in PRs that break the deploy to AWS  on merge to master

Add job to CI to ensure validity of docker builds

---

common/tests/__snapshots__/prereq_loader.test.js.snap

Rerun tests to no longer include information on 4501 since the recitation no longer exists and should not be expected to be in SearchNEU's scraper

Fix Failing Tests

---

frontend/src/home/AddPlanPopper.tsx

Handled the following tickets:
https://trello.com/c/N0EP4QeB/180-create-plan-based-on-dropdown-border-overlaps-with-title-within-create-plan-popper
https://trello.com/c/x1p7LIAR/173-typo-in-create-plan-popper-when-creating-new-plan-from-existing-plan
https://trello.com/c/r8XKXASe/177-create-plan-popper-shows-an-error-when-submitting-without-setting-a-major
https://trello.com/c/yC39m66H/179-create-plan-popper-says-select-a-co-op-cycle-within-dropdown-for-selecting-an-existing-plan

Add Plan Popper Errors

---

frontend/src/state/index.ts
frontend/src/state/reducers/scheduleReducer.ts

Switch redux props for closed years to be an array instead of a set to avoid deep copying errors

Fix Deep Copying Error caused by Closed years

---

frontend/src/state/actions/advisorActions.ts
frontend/src/state/actions/index.ts
frontend/src/state/reducers/advisorReducer.ts
frontend/src/state/reducers/state.ts

https://trello.com/c/sxNN1KLs
We need to draft out the design of the Redux store for the advisor work flow as we start getting into implementing it.
- Create an `AdvisorState` interface containing basic session data along a list of students for use in both the students tab and when searching students to assign a template to
- Add the `advisorReducer` along with advisor actions
We are currently settling with not persisting data like notifications or templates within the Redux state and requesting them as needed since they are only used in a single location each. Students on the other hand will be cached in Redux after the first request so it can be reused across both the students tab and when assigning templates to students.
Please let us know if there are any concerns with this approach!

Set up Redux Store for Advisors

---

frontend/src/Onboarding/RedirectScreen.tsx
frontend/src/components/Routes/ProtectedRoute.tsx

ShallowEqual is necessary for proper rerenders when we use `useSelector` in this way (returning one object with everything), as opposed to one `useSelector` call per field we want from redux.

use shallow equal

---

frontend/src/api/index.ts

Search fixed their CORS headers. Therefore, we no longer need the proxy.

Remove proxy

---

frontend/src/Onboarding/OnboardingInfoScreen.tsx
frontend/src/Onboarding/TransferableCreditScreen.tsx
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/home/EditPlanPopper.tsx
frontend/src/home/Home.tsx
frontend/src/models/types.ts
frontend/src/state/actions/userActions.ts
frontend/src/state/actions/userPlansActions.ts
frontend/src/state/index.ts
frontend/src/state/reducers/userPlansReducer.ts

- We should use null instead of undefined/empty string in a lot of places
- Only go to completed courses screen if the user selected a major
- Overhaul onboarding info screen to handle major given from khoury data

Save null (not empty string) in db for major, coopCycle, catalogYear if blank

---

api/app/controllers/plans_controller.rb
api/app/models/user.rb
api/app/views/users/_user.json.jbuilder
api/config/routes.rb
api/db/migrate/20210101193734_add_primary_plan_id_to_user.rb
api/db/schema.rb
api/test/fixtures/users.yml
api/test/models/user_test.rb
common/types.ts
frontend/src/Onboarding/TransferableCreditScreen.tsx
frontend/src/home/EditPlanPopper.tsx
frontend/src/models/types.ts
frontend/src/services/PlanService.ts
frontend/src/state/index.ts

Allows students to set a primary plan for an advisor. We should iterate on what the best UI is to indicate a primary plan to a user. Maybe we replace "Plan of Study" with "Your Primary Plan" or the plan name if it's not primary?

Set primary plan

---

common/tests/__snapshots__/prereq_loader.test.js.snap
frontend/src/advising/Templates/TemplateInfoPage.tsx

We need a way for advisors to create new folders.
- Replace the existing existing folder selection on the `TemplateInfoPage` with a new `FolderSelection` component that provides the option to either choose an existing folder or create a new folder
- For the future, I'm going to also revamp the error handling on this page to match that of the other pages, i.e. having individual errors for each form that display when pressing next
- There is some minor styling wonkiness when switching between inputs (they have different heights)
- We are definitely going to need to think about providing the option to delete folders as well + what the intricacies of that are going to be
- We eventually will want to give the option to create an empty folder from the list page

Add option to create from existing or new folder on TemplateInfoPage

---

frontend/src/utils/generate-warnings.ts
frontend/src/utils/requirementGroupUtils.ts

This is a subtask on this ticket: https://trello.com/c/rkcjckMU/30-update-requirement-group-validation-in-the-sidebar
Sort the requirement groups based on type of IMajorRequirementGroup, from most to least constrained, with most being AND and least being RANGE. 
Example use case for sorting is that we'd want to validation concentration courses before validating electives

sort validation based on group type

---

frontend/src/advising/Templates/TemplateInfoPage.tsx

There is an issue with how the folder name input field looks if the advisor has no existing folders. This was because the field's width property was set to 100%.
Sets a static width of 326px for the input field to match the other fields.

Fix 100% width for folder name on TemplateInfoPage

---

common/types.ts

The word max was misspelled as mas

Fixed typo

---

frontend/src/Onboarding/OnboardingInfoScreen.tsx
frontend/src/home/EditPlanPopper.tsx
frontend/src/plans/coopCycles.ts
frontend/src/profile/Profile.tsx
frontend/src/state/reducers/userPlansReducer.ts

[Ticket](https://trello.com/c/5ST3Q0EJ)
We want users to be able to select co-op cycles that don't have a corresponding plan.
- Compute and export a static constant which contains co-op cycle options
- Use these options in co-op cycle dropdowns
- In the `EditPlanPopper`, conditionally display the `SET EXAMPLE SCHEDULE` button based upon if there is an available schedule
- This only exposes the new co-op cycles and allows them to be selected and persisted, schedules are not yet able to update to match them (I was told this would be future work)
- I did not add this to the `AddPlanPopper` because of the above point

Add additional co-op cycle options 

---

frontend/src/advising/Templates/TemplateBuilderPage.tsx
frontend/src/components/ClassBlocks/ClassBlock.tsx
frontend/src/components/ClassBlocks/ClassBlockBody.tsx
frontend/src/components/Schedule/ScheduleComponents.tsx
frontend/src/components/SemesterBlock.tsx
frontend/src/components/Sidebar/GenericClassBlock.tsx
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/constants/index.ts
frontend/src/state/actions/userPlansActions.ts
frontend/src/state/index.ts
frontend/src/state/reducers/userPlansReducer.ts
frontend/src/utils/dnd-helpers.ts

https://trello.com/c/9bYmxEUf/315-create-xxxx9999-block-for-advisors-to-use-on-their-template-plans
Adds generic course block to sidebar in template builder view for advisors. Only advisors can edit the name of the generic course blocks.

Generic class block

---

frontend/src/App.tsx
frontend/src/advising/ManageStudents/ExpandedStudentView.tsx
frontend/src/advising/ManageStudents/GenericStudentView.tsx
frontend/src/advising/ManageStudents/StudentView.tsx
frontend/src/components/Schedule/ScheduleComponents.tsx
frontend/src/state/actions/studentActions.ts
frontend/src/state/reducers/studentReducer.ts

Display the transfer credits a student has taken by adding student to redux.
- Abstracted Student View and Expanded Student View into Generic Student View component
- Reduces number of API calls by keeping student in the redux state between the Student View and Expanded Student View
- Removes the student from the state when navigating away from the Student View and Expanded Student View
https://trello.com/c/S61Y7NXW/314-add-student-transfer-courses-to-redux-when-advisor-selects-them

Add student transfer to redux

---

frontend/src/home/AddPlanPopper.tsx
frontend/src/hooks/useForm.ts

https://trello.com/c/i3oYMCc6
Making forms is hard. Making forms with validation is harder. Abstracting logic for validating forms is... ☹️ 
All of our forms that cleanly validate errors are difficult to set up and maintain, and there is a lot of common logic repeated across them. It would be nice to have some of this abstracted away to make things a little less painless or at least slightly more organized and readable. 
I ultimately decided not to pull in a library that handles this because it would probably just come with way more than we actually need and require too much setup than is worth, plus we'd need to pull in another whole bunch of dependencies when we could just make our own in-house lightweight alternative.
Questionably improves our form validation by adding a `useForm` …

Proof-of-concept to add useForm hook for handling form state and validation AddPlanPopper

---

frontend/src/components/ClassBlocks/ClassBlock.tsx
frontend/src/components/SemesterBlock.tsx
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/Year/YearTop.tsx
frontend/src/home/Home.tsx
frontend/src/state/reducers/userPlansReducer.ts
frontend/src/utils/deepCopy.ts
frontend/src/utils/schedule-helpers.ts

Currently, if you spend hours working on your schedule and have an epiphany that you want to change the co-op cycle, you basically loose EVERYTHING without any warning whatsoever. We need to change this so that people don't rage and throw their machines out the window.
https://user-images.githubusercontent.com/30478978/139556447-eeb4a274-25d5-40c2-b891-58d363a803dd.mov
- The reducer responsible for handling the change co-op cycle action now fills in the new schedule with the schedule the user has already created. This is done using the `fillInSchedule` helper function in schedule-helpers.ts
- A new map was added to the UserPlansState. It maps a plan name to its fifth year cache. The fifthYearCache is the most recently planned fifth year schedule and is handy to fill in the 5th year when …

Stop schedule from being wiped when changing Co-op cycle

---

frontend/src/utils/fetchMajorsAndPlans.ts

We were not able to fetch data because of API change. In the screenshot we see the "data" field is now a promise instead of the major objects. This PR adds a "then" so that it waits for data to resolve.

await nested promise

---

frontend/src/api/index.ts

There was a bug requesting classes from the search api, with the following error
Manual testing: 
clicked "+ Add Class" button and searched for class. Before, the page is stuck in loading and in the network tab we see errors. 
After this fix, classes are successfully fetched.

fix search classes bug

---

.github/workflows/aws-cd.yml

Broke CD workflow with the yarn workspaces PR. More specifically, renamed the deploy directory to prod but didn't rename it in the aws workflow 😔
Updated CD branch name to current branch to run the workflow - https://github.com/sandboxnu/graduatenu/runs/5653699101

Fix redeploy script path in aws cd workflow

---

packages/frontend-v2/components/Error/ClientSideError.tsx
packages/frontend-v2/components/Error/ErrorBoundary.tsx
packages/frontend-v2/components/Error/index.ts
packages/frontend-v2/components/index.ts
packages/frontend-v2/package.json
packages/frontend-v2/pages/_app.tsx
packages/frontend-v2/pages/index.tsx
packages/frontend-v2/utils/index.ts
packages/frontend-v2/utils/logger.ts
packages/frontend-v2/utils/toast.ts
yarn.lock

Basic error handling(toasts for api errors, error boundary for client side) and logging.
- Added a logger utility that simply wraps console.log functionality. As our application matures, the logger can be made more sophisticated.
- Added a toast utility to display toasts using react-toastify. Currently a simple wrapper over react-toastify but the logic will mature as needed + we can easily migrate to another library/update the toast logic across the application.
- Added an ErrorBoundary that renders a very basic error page for now. Once, material UI and styled components are configured, the error page will be styled.
Closes [Error Handling](https://trello.com/c/QFjxMXRJ/430-error-handling)
Buttons on the landing page to trigger all of the …

Add toasts, logging, and error boundary

---

packages/scrapers-v2/tsconfig.json

After https://github.com/sandboxnu/graduatenu/pull/413 was merged, the CI build failed because scrapers-v2's tsconfig is missing some options. Since we are using decorators in `dto-types`, we need to add `experimentalDecorators` to the config (more info see [here](https://www.typescriptlang.org/docs/handbook/decorators.html)). Additionally, we also initialize without having constructors in `dto-types`, so we also need an option for `strictPropertyInitialization` (see [here](https://www.typescriptlang.org/tsconfig#strictPropertyInitialization)). 
Though I am not sure why CI build wasn't catching it before in the branch... unless the dto stuff was merged after. 
Provide …

Fix CI Build

---

.husky/common.sh
.husky/pre-commit
package.json
yarn.lock

when we upgraded to yarn2, husky stopped working. this PR fixes that.
to fix, i followed the [automatic install instructions](https://typicode.github.io/husky/#/?id=automatic-recommended) for yarn2, additionally following the [yarn on windows](https://typicode.github.io/husky/#/?id=yarn-on-windows) fix for git bash.
the new way of writing hooks, it seems, is by running `yarn husky add .husky/<name> '<command>'`, which writes to a file of the specified name in the `.husky` directory.
1. `yarn install`
2. edit a *.ts file to have incorrect formatting
3. `git add .` and `git commit`
4. `git diff HEAD~1`
5. verify that the formatting was fixed in the commit (by pretty-quick)
it would be great if someone could test out the changes on windows with …

Make husky work for yarn2

---

packages/api-v2/src/auth/auth.controller.ts
packages/api-v2/src/auth/auth.service.ts
packages/api-v2/src/student/entities/student.entity.ts
packages/api-v2/src/student/student.controller.ts
packages/api-v2/src/student/student.service.ts
packages/common/src/dto-types.ts
packages/common/src/response-types.ts

This PR is an update to the current `api-v2` backend where it now follows through with the Onboarding and Signup flow discussions held during component design. In more specific the implemented flow is as follows:
User signs up 
-> Information saved in backend, with all fields apart from `email`, `password`, and `uuid` set to null
-> Client side, user is redirected to onboarding
-> PATCH request to update the user after onboarding by sending a request to `/api/students/me/onboard`
-> Backend route requires for all fields to be present, then will update the user in db accordingly as well as set `isOnboarded` field of the user to be true
This implementation can be further looked at [here](https://www.notion.so/sandboxnu/Signup-Login-Design-dce4ba0d1c9f4eb3920490b9a43e1743).
Run the …

Updates the Backend to Support Onboarding Flow

---

packages/api-v2/src/auth/auth.controller.ts
packages/api-v2/src/student/entities/student.entity.ts

This PR addresses two bugs from the JWT PR oops. 
1. One was brought up by @BrandonLim8890 that the password field was being returned after registering/logging. `Exclude` decorator is being ignored when destructuring a student object. Solution: add `Exclude` to accessToken and return the student object.
2. When there is no accessToken (when email cannot be found or wrong pw), it returns 500 instead of 401. Solution: reordered destructuring and checking unauthorized.
Provide instructions so we can reproduce. 
No pw or accessToken returned
Try it [here](https://www.getpostman.com/collections/46cd58bffd04d405ea47)

Fix JWT PR Bug

---

packages/common/test/assets/postman-api.json

This PR updates the example Postman queries provided to work with our API. 
**[Fix]:** Fixed the create the create plan query (POST /api/plans/). This was not working properly because it assumed the v1 plan type, and has now been updated to work with v2 plans.
**[Fix]:** Fixed the Register Student endpoint (POST /api/auth/register). This was not working properly because it needed the passwordConfirm field in the body. 
**[Added]:** Added a Delete Plan query to the options as it was available in our API, but not provided as an example query.

Documentation - Update Example Postman Queries

---

packages/frontend-v2/components/Form/Input.tsx
packages/frontend-v2/components/Form/Select.tsx
packages/frontend-v2/components/Form/index.ts
packages/frontend-v2/components/Plan/AddPlanModal.tsx
packages/frontend-v2/components/Plan/EditPlanModal.tsx
packages/frontend-v2/components/Plan/index.ts
packages/frontend-v2/pages/home.tsx

Add an Edit Plan button that edit the name, catalog year and the major of the current plan
https://user-images.githubusercontent.com/75349763/196054929-72af0aff-65a4-48e0-aefb-5a6da41d9da4.mov
Closes #452
- [ x ] Checking the data changes using Postman

Add Support To Edit An Existing Plan

---

packages/api-client/index.ts
packages/frontend-v2/components/Sidebar/SectionRequirement.tsx

Small fix to get class credits information from Search's API. Also made missing courses display their subject + classId so it's easier to debug missing classes later and provides some extra info to users.
Closes #492
Manually tested by checking that the credits add up properly in the semesters now.

Add credit information to sidebar class data

---

packages/frontend-v2/utils/plan/preparePlanForDnd.ts

There was a change made that broke increasing IDs in the preparePlanForDnd function which meant that when you tried to drag one class, it would often drag another with the same subject + classId as they had identical IDs.
Closes #497 
I confirmed that drag-and-drop IDs now increase for every class again using React Dev Tools and made sure that classes with the same subject + classId can be dragged properly and independently.

Fix drag-and-drop IDs not increasing in plan properly

---

packages/frontend-v2/components/Plan/Plan.tsx
packages/frontend-v2/components/Plan/ScheduleYear.tsx

Fixes styling in Safari and brings the styling more in-line with the current styling plans on Figma.
Styling in Safari with this PR:
Closes #483 
I manually checked to see if it looks right and drag-and-drop still works properly in Safari, Firefox, and Microsoft Edge (chromium).

Fix Safari Styling Issues

---

packages/common/src/index.ts
packages/common/src/major2-validation.ts
packages/frontend-v2/components/Sidebar/Sidebar.tsx
packages/frontend-v2/components/Sidebar/SidebarSection.tsx
packages/frontend-v2/pages/home.tsx
packages/frontend-v2/utils/plan/getAllCoursesFromPlan.ts
packages/frontend-v2/utils/plan/getSectionError.ts

https://user-images.githubusercontent.com/2746893/202877856-ecaacbcb-fe57-4f30-bd4c-9c08207afee5.mp4
This PR adds allows users to see major validation information in the sidebar. It also has small styling tweaks to the sidebar sections. 
There are still a few issues (validation algorithm bug and performance issues with near-full schedules) that should be resolved regarding major validation before alpha, but this PR will introduce the core functionality.
Closes #489 
This has been tested manually by trying various schedules in Firefox.

Displaying Major Validation in the Sidebar

---

packages/common/src/major2-validation.ts
packages/common/test/major2-validation.test.ts
packages/frontend-v2/components/Sidebar/Sidebar.tsx
packages/frontend-v2/components/Sidebar/SidebarSection.tsx
packages/frontend-v2/utils/plan/getSectionError.ts

https://user-images.githubusercontent.com/2746893/204439039-02577a94-3157-4445-acc9-061a3dfd3c01.mp4
Fixes an edge case where courses could be double counted because major validation could only return either an AndUnsatRequirements error or a AndNoSolution error but not both. As a result if there were any unsatisfied children in an And it would mask the NoSolution error, resulting in not enough errors being returned. This caused the UI to check off both sections despite such a solution being impossible.
Also makes some code clarity changes to how the section errors are propagated.
Closes #503 
This has been manually tested and some automated tests were added in `major2-validation.test.ts` that cover the case that this fixes.

Fix Major Validation Double-Counting

---

packages/frontend-v2/components/Sidebar/Sidebar.tsx
packages/frontend-v2/components/Sidebar/SidebarSection.tsx

Adds a loading message to the sidebar sections while we wait for the Search API request to come back.
https://user-images.githubusercontent.com/2746893/205402507-ec7f3a3a-019f-406f-8434-5cc290da75f7.mp4
Closes #490 
Manual tests to check that this works as intended both when the API request succeeds and fails.

Add a loading indicator to Sidebar sections

---

packages/api-client/index.ts
packages/common/src/types.ts
packages/frontend-v2/components/Plan/Plan.tsx
packages/frontend-v2/components/Plan/ReqErrorModal.tsx
packages/frontend-v2/components/Plan/ScheduleTerm.tsx
packages/frontend-v2/components/Plan/ScheduleYear.tsx
packages/frontend-v2/components/ScheduleCourse/ScheduleCourse.tsx
packages/frontend-v2/pages/home.tsx
packages/frontend-v2/utils/course/getCourseCoreqs.ts
packages/frontend-v2/utils/plan/preAndCoReqCheck.ts
packages/frontend-v2/utils/theme/components/buttons.ts

Added coreq/prereq errors for classes. Displays error icon in the year as well as on the specific class. The error Icon on that class opens a modal that tells you specifically what classes you can take to satisfy the error.
Next steps are to add more styling and pagination to the modal.
Another step is also to address the Prop drill down issue, where we would instead use context for the errors.
https://user-images.githubusercontent.com/20482676/200195253-07339502-a79b-414f-8621-19a9c4328bfe.mp4
Closes #454
Provide instructions so we can reproduce. 
Tested with dragging in coreq/prereq errors and checking if they were giving the correct errors as well as if they went away when we added the correct classes.

Frontend Coreq and Prereq Errors

---

packages/api-v2/src/major/majors/2022/bscs.json

This PR fixes a typo in the BSCS Major (4 required subsections in a section where there were only 3). This prevented the "Computer Science Fundamental Courses" section from being completed in the UI as it returned an error in major validation.
Manually tested with the validation algorithm UI.

Small BSCS Major Fix

---

infrastructure/prod/Dockerfile.app
infrastructure/prod/Dockerfile.server

This PR silences the stdout logging of the yarn install in our two Dockerfiles. This it to make the output more readable so we can more easily see the reason a CI is error-ing. Right now, the yarn install logs ~5,000 lines (see below), which pushes the relevant error very far down into the logs.
I manually rebuilt the Dockerfiles and sanity checked that redirecting the output didn't break anything.

Silence yarn install in Dockerfiles

---

babel.config.js
packages/api-v2/nest-cli.json
packages/api-v2/package.json
packages/api-v2/src/auth/auth.controller.ts
packages/api-v2/src/auth/auth.service.ts
packages/api-v2/src/main.ts
packages/api-v2/src/major/major.controller.ts
packages/api-v2/src/plan/plan.controller.ts
packages/api-v2/src/plan/plan.service.ts
packages/api-v2/src/student/student.controller.ts
packages/api-v2/src/student/student.service.ts

- We have a common package with API response types
- We use babel to build the common package
- We fail to build these types in a way that is compatible with class transformer library used in the API
- Hence, instead of using the build we simply import the types directly from the file using the path which isn't the pattern used in the codebase
- After some stackoverflowing, I realized that we need the @babel/plugin-proposal-class-properties plugin after the @babel/plugin-proposal-decorators plugin in our babel config to build properly.
Closes #517 
- yarn dev:v2 works
- yarn prod:v2 works: this uses production build for common

Fix build issues with class transformer and api

---

packages/api-client/index.ts
packages/frontend-v2/components/AddCourseModal/AddCourseModal.tsx
packages/frontend-v2/components/Plan/Plan.tsx
packages/frontend-v2/components/Plan/ScheduleTerm.tsx
packages/frontend-v2/components/Plan/ScheduleYear.tsx
packages/frontend-v2/components/Sidebar/Sidebar.tsx
packages/frontend-v2/hooks/useFetchCourses.ts
packages/frontend-v2/utils/course/getCourseCoreqs.ts

Update course fetching to be by catalog year (getting all occurrences of a course and filtering by catalog year), fallback to latest occurrence of the course 
Closes # (519)

Implement courses by catalog year

---

packages/frontend-v2/pages/home.tsx

Adjusted the useEffect in home.tsx so that upon loading the page we find the latest plan created by the user 
and displays it instead of simply displaying a blank screen and waiting for the user to choose a plan. 
Closes # 551
Created a new user with no plans and made sure the same behavior as before is performed. Created a student 
with one plan to test if it worked with a list of one. Made a student with multiple plans and see if it displays the 
correct plan.

Dylan rework blank screen

---

.github/workflows/main.yml

Scraper tests are currently only passing rarely and don't actually measure anything useful for the vast majority of commits. We'll likely revisit these once the new scraper code is committed to this repo or a standalone repo.

Banish Scraper Tests to the Shadow Realm

---

packages/common/src/types.ts

Adds an optional `warnings` field to sections to allow us to mark things we don't validate.

Try to Warn Users of Impending Doom (Add Warning Labels to Sections)

---

packages/frontend-v2/pages/home.tsx

Somehow the updatedAt property is being sent as a string somewhere along the process so when `getTime` is called, it crashes the app. To prevent this, I'm just converting the dates explicitly. This has no effect on existing dates (so it's safe to include even if the issue isn't consistent), but converts strings to the correct date, allowing the `getTime` method to be run.
Something is wrong somewhere else in the app that's causing this, but this mitigates the symptoms in the short term.
Manually tested to check that this fixes the problem.

Hotfix for multiple plans

---

packages/frontend-v2/components/Header/AccountOverview.tsx

Added conditional rendering for the send email verification link in the account overview
Closes #622

Conditional rendering for 'email not verified' in account overview

---

packages/api-v2/src/major/major.service.ts
packages/api-v2/src/plan/plan.errors.ts
packages/api-v2/src/plan/plan.service.ts

Closes #512
Postman Tests are described below.
This purpose of this bug fix is to ensure that users cannot create a plan with a concentration, and then switch majors without updating the concentration information. For example, let us say that there is a BSCS plan with AI concentration. Let us say that this person updates the plan to a CS & Business Admin, but does not update the concentration from AI. (CS & BA doesn't have AI concentration, but it has different concentrations). 
Hit the Create Plan endpoint:
Request Body:
```
{
    "name": "Plan 2", …
```

Dylans concentration update 512

---

packages/frontend-v2/pages/home.tsx
packages/frontend-v2/utils/plan/preAndCoReqCheck.ts

Closes #613 
Adding a course that requires a pre-req (ex: Interdisciplinary Advanced Writing in the Disciplines), and making sure the pre-req error disappears when adding the required course in Transfer Courses (ex: First Year Writing). 
Transfer courses should not apply to co-reqs, only pre-reqs.

User transfer courses when generating pre-req errors (#613)

---

packages/api-v2/src/graduate-logger.ts

We are currently logging the passwordConfirm field production which is bad security practice. This PR removes the field by adding it to the denylist.
Tested locally.

Add "passwordConfirm" to Logging Denylist

---

packages/api-v2/src/student/student.service.ts
packages/common/src/api-dtos.ts
packages/frontend-v2/components/Header/AccountOverview.tsx
packages/frontend-v2/pages/signup.tsx

Removed references to first/last name in FE and replace it with full name.
There's also some formatting changes (RIP) 
Closes #583

Use full name instead of first/last

---

packages/api-v2/.env.development
packages/api-v2/src/email/email.module.ts
packages/frontend-v2/pages/home.tsx
packages/frontend-v2/utils/plan/preAndCoReqCheck.ts

Set a timeout on confirmation links sent out in emails, so that they expire after 15 minutes. Fixed the JWT token to expire after a day, as well.
Closes #556 
**Changes to .env file, please make sure your copy of it is changed as well!**
- Manually tested -- you can create a new account and wait 15 minutes before clicking on the confirmation link. The confirmation should not go through!

Email jwt timeout

---

package.json
packages/api-v2/src/app.module.ts
packages/api-v2/src/auth/auth.controller.ts
yarn.lock

Implement rate limiting on all endpoints. Limits to 100 max per minute on all endpoints except the login endpoint which is limited to 20 max per minute. This is on a per-IP basis (i.e. every person accessing the app gets the 100 max requests per minute)
Closes #569 
Tested exceeding limit and it was successfully throttled

Implement rate limiting

---

packages/api-v2/src/main.ts

Add a temporary Vercel URL to the allowlist for the backend, so that we can test the new setup (Vercel frontend) in staging.

feat: allow temp vercel URL as origin (CORS)

---

packages/frontend-v2/components/ScheduleCourse/ScheduleCourse.tsx

Previously, hovering over a transfer course changed cursor to a grab, and made it look like you could drag the course when you can't. This PR just fixes that by removing the hover animations .
Closes #654

Remove transfer course cursor styling

---

packages/frontend-v2/package.json
yarn.lock

This reverts commit e06a0e27f1edf14e7a26cd8c2b9f95d03a6f71df.
Hotfix to fix a spiraling staging build.

Revert "Bump next from 12.3.1 to 13.5.0 (#642)"

---

packages/frontend-v2/pages/home.tsx

On application load, we should be loading the most recently used plan. However, we currently load the last used plan due to a small logic error in our sorting. This PR simply updates the sorting algorithm to ensure that we use the last modified plan.
Closes #673
1. Ensure that you have 2 plans loaded
2. Update plan A, refresh the page and plan A should be the default plan loaded upon refresh
3. Make a change to plan B, refresh the page and plan B should be the default plan loaded upon refresh.

Fix default plan on page load

---

packages/frontend-v2/components/ScheduleCourse/ScheduleCourse.tsx
packages/frontend-v2/components/Sidebar/SectionRequirement.tsx

Adds support for a checkmark to appear in a course when it's in the sidebar, if the course has been added to the plan. Added attributes "isInSidebar" and "isChecked" in `DraggableScheduleCourse` component in order to enable this.
Validation is not implemented yet! This only adds support for when validation is good to go :)
Closes #652 
- Manually tested

Support for checkmarked courses in sidebar

---

packages/frontend-v2/components/Error/ClientSideError.tsx

Quick fix to make the error boundary redirect to `/home` regardless of the current domain.
Closes #682.
Tested manually locally.

Make Error Boundary Home Link Domain-Agnostic

---

packages/frontend/components/Plan/DeleteYearModal.tsx
packages/frontend/components/Plan/ScheduleYear.tsx
packages/frontend/hooks/useRedirectIfLoggedIn.ts

When deleting a year, a modal opens for the user to confirm whether they want the year to be deleted.
https://github.com/sandboxnu/graduatenu/assets/30753067/645be1e1-c8f2-4230-8842-c86bdcfc3362
Closes #685 
Tested manually for account users and guests.

Add a confirmation modal when deleting a year

---

packages/frontend/components/Plan/DeleteYearModal.tsx

Prevented the delete year modal button from trigging the expansion of the year pane. Before, the onClick event on the delete button triggered the expansion of its year. This is not fixed and clicking the delete button does not expand the year.
Closes #693 
https://github.com/sandboxnu/graduatenu/assets/30753067/90f07df3-6f35-489b-ba28-c7b7407ce883

Prevent delete year modal from expanding year

---

packages/frontend/pages/index.tsx

Closes #644. Adds the "Ready to get started" section on the landing page. Doesn't display on mobile.

Add ready to get started section

---

packages/frontend/components/Form/Select.tsx
packages/frontend/components/Plan/AddPlanModal.tsx
packages/frontend/components/Plan/EditPlanModal.tsx
packages/frontend/components/Plan/PlanConcentrationsSelect.tsx

Closes #696 
Use react-select's placeholder attribute which lets you set placeholder text that is gray instead of black. Replaced noValueOptionLabel with placeholder which also removes the default value option from the list.
Other minor changes:
- Concentrations -> Concentration
- Tweaked colors of select dropdown to match input box
Before:
https://github.com/sandboxnu/graduatenu/assets/92692008/95716e7d-524c-4821-9b9c-6b9dd74c3fcc
After:
https://github.com/sandboxnu/graduatenu/assets/92692008/66f4ec1a-0a29-4799-98ee-6b2777b7aa4f

Select use placeholder

---

packages/api-client/index.ts
packages/common/src/types.ts
packages/frontend/components/AddCourseModal/AddCourseModal.tsx
packages/frontend/components/AddCourseModal/NUPathCheckBox.tsx
packages/frontend/components/AddCourseModal/NUPathLabel.tsx
packages/frontend/components/AddCourseModal/SearchCoursesInput.tsx
packages/frontend/components/AddCourseModal/SearchResult.tsx
packages/frontend/components/AddCourseModal/SelectedCourse.tsx
packages/frontend/components/Error/ConfirmEmailWarningModal.tsx
packages/frontend/hooks/useSearchCourses.ts
packages/frontend/utils/course/countFilteredPaths.ts
packages/frontend/utils/course/sortCoursesByNUPath.ts
packages/frontend/utils/theme/components/buttons.ts

Closes #668
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code where needed
- [ x] My changes generate no new warnings

Nu path modals/frontend add course modal 668

---

packages/frontend/components/AddCourseModal/AddCourseModal.tsx
packages/frontend/components/AddCourseModal/NUPathCheckBox.tsx
packages/frontend/components/AddCourseModal/NUPathLabel.tsx
packages/frontend/components/AddCourseModal/SearchResult.tsx
packages/frontend/components/AddCourseModal/SelectedCourse.tsx
packages/frontend/components/Button/SecondaryButton.tsx
packages/frontend/components/Button/index.ts
packages/frontend/components/Plan/ScheduleTerm.tsx
packages/frontend/components/Plan/TransferCourses.tsx
packages/frontend/components/ScheduleCourse/CourseDragIcon.tsx

Tweaked size, color, spacing of stuff in the Add Course modal. Also created a `SecondaryButton` component.
I also realized from these screenshots that NUpath selections are saved when closing and reopening the modal but is not visually represented as so. We should just clear the selections when the user closes the modal. Created a new issue for that [here](https://github.com/sandboxnu/graduatenu/issues/716).
Before:
After:
Closes #715 

Angela/add course modal UI tweaks

---

packages/frontend/components/Sidebar/SectionRequirement.tsx

Fixes the classCode being truncated for exceptions in ranges in the sidebar.
|Before |After |
|-|-|
|<img width="360" alt="Screenshot 2024-03-24 at 3 24 23 PM" src="https://github.com/sandboxnu/graduatenu/assets/2746893/ed602af9-9108-48e8-b2b3-4763b79cf703"> | <img width="361" alt="Screenshot 2024-03-24 at 3 24 14 PM" src="https://github.com/sandboxnu/graduatenu/assets/2746893/dc86c7a4-15f1-448a-8ca9-13982944e2cb">|

Small sidebar fix

---

packages/frontend/components/Help/HelperTooltip.tsx
packages/frontend/components/Plan/ReqErrorModal.tsx
packages/frontend/components/Sidebar/DropdownWarning.tsx
packages/frontend/components/Sidebar/Sidebar.tsx
packages/frontend/components/Sidebar/SidebarSection.tsx
packages/frontend/utils/constants.ts
packages/frontend/utils/theme/index.ts

Adds the following warnings:
1. A warning over the sidebar stating again that its not fully accurate, even for majors that we have checked -- [Here](https://www.figma.com/file/yUflVFVxjMynm7gGymLpQY/%F0%9F%8F%97-Current-Work?type=design&node-id=5741%3A34919&mode=design&t=q0ALpY9SOwwxBltM-1)
2. Warning over certain requirements within a major that we have hand-validated -- [Here](https://www.figma.com/file/yUflVFVxjMynm7gGymLpQY/%F0%9F%8F%97-Current-Work?type=design&node-id=5789%3A16400&mode=design&t=11hrbc3dIkpkMrH4-1)
4. Pre req/co req warning -- [Here](https://www.figma.com/file/yUflVFVxjMynm7gGymLpQY/%F0%9F%8F%97-Current-Work?type=design&node-id=5789%3A16504&mode=design&t=11hrbc3dIkpkMrH4-1)
https://github.com/sandboxnu/graduatenu/assets/20124104/77b8f44a-349d-4d22-850d-7c22cac15371 …

Add remaining warnings

---

packages/frontend/components/Sidebar/Sidebar.tsx

Dont show the heads up dropdown if for no major plans.

Remove heads up warning for no major

---

packages/frontend/components/Plan/AddPlanModal.tsx

Adds a small message regarding missing majors
- [] I have run the production builds in docker for the frontend/backend and ensure things run fine. Check README of repo on how to run if not sure.

Add msg for missing majors

---

packages/frontend/components/Sidebar/NUPathSection.tsx
packages/frontend/components/Sidebar/Sidebar.tsx

Added an if statement where courses are assigned their NUPaths and made sure to check that if a course was a co-op, then the EX NUPath was fulfilled. 
Closes # (742)
Dragging a co-op block onto the degree planner and making sure it gives the correct nupath

Coops fulfill Integrated Experience NUPath

---

README.md
packages/frontend/components/Sidebar/Sidebar.tsx
packages/frontend/pages/home.tsx
packages/frontend/utils/plan/totalCredits.ts

Shireen and I added the function to calculate the total amount of transfer credit on both types of sidebars (major and non-major). We changed the parameters to take in transferCourses on the non-major sidebar. The function calculates the sum and adds it to the totalCreditsInSchedule to get creditsTaken. 
For the future, maybe add AP courses on the "Add transfer courses" modal so the user doesn't have to look up the AP to NEU course transfer policies.

Transfer credits now add up to total credits on sidebar

---

package.json
packages/common/src/major2-validation.ts
packages/common/src/types.ts
packages/frontend/components/Sidebar/NUPathSection.tsx
packages/frontend/components/Sidebar/Sidebar.tsx
packages/frontend/components/Sidebar/SidebarSection.tsx
yarn.lock

I added a new SidebarValidationStatus that marks sections, concentrations, and NUPaths as 'in progress,' using a dedicated icon whenever any of them are in progress.
Closes # (751)
via inspection

in progress display for a section once it's in progress

---

packages/frontend/components/Plan/AddYearButton.tsx
packages/frontend/utils/plan/addEmptyDndYearToPlan.ts

It doesn't make sense to have a plan for more than five years. Now the button to add a year will be disabled if there are already 5 years in your plan.
Closes # (762)
- [] I have run the production builds in docker for the frontend/backend and ensure things run fine. Check README of repo on how to run if not sure.

capped years at 5

---

packages/frontend/components/Plan/Plan.tsx
packages/frontend/components/Plan/ScheduleTerm.tsx
packages/frontend/components/Plan/ScheduleYear.tsx
packages/frontend/utils/plan/removeCourseFromTerm.ts

Adding index to filtering logic for generic/NUPath course deletions

---

packages/common/src/major2-validation.ts

It seems like some of the JSON from the 2024-2025 catalog year majors were causing the major validation algorithm to crash and there were two common culprits:
1. A requirement section was scraped with no requirements, which threw an error in the validator. Ideally, no major should have a shape where there are no requirements in a section but this PR just suppresses this error by returning Ok.
2. Some requirement sections seem to have scraped requirements with nested arrays. This is an issue that was also causing crashes on the frontend that Shireen has solved. The shape of the inner elements of the arrays seem valid, so there is some code to "unpack" these nested section requirements
Please describe how you tested …

Major Algorithm Patch 

---

packages/frontend/components/Sidebar/SectionRequirement.tsx
packages/frontend/components/Sidebar/Sidebar.tsx
packages/frontend/components/Sidebar/SidebarSection.tsx

Added a new prop to the SectionRequirement so that once all the courses are rendered they can check if they exist in the student's plan. If they do, then they will be displayed with a checkmark.
Closes # 776

Courses in sidebar will display a checkmark if they are present anywhere in the users plan

---

packages/api/package.json
yarn.lock

update bcrypt version

---

packages/frontend/components/Plan/ErrorModalError.tsx
packages/frontend/components/Plan/Plan.tsx
packages/frontend/components/Plan/ReqErrorModal.tsx
packages/frontend/components/Plan/ScheduleTerm.tsx
packages/frontend/components/Plan/index.ts
packages/frontend/components/ScheduleCourse/ScheduleCourse.tsx
packages/frontend/utils/constants.ts

Adds a new error component for the error modal, which is general and can be reused for other errors. This PR renders the error component when trying to place Co-op classes in the Fall of your first semester or Spring of your last semester.
Closes [#791](https://github.com/orgs/sandboxnu/projects/18/views/1?pane=issue&itemId=93026220&issue=sandboxnu%7Cgraduatenu%7C791)

Modal Error Component + Co-op in first/last semester bug

---

packages/frontend/components/Plan/AddPlanModal.tsx

Updated form validation. Title is no longer required. This is because the value is set to `Plan [timestamp]` if value is empty. `Plan [timestamp]` is also placeholder value for plan. Hopefully not too expensive to get timestamp. 
EDIT 2/18: Added catalog year + major name to the default name. kept date and time to prevent repeated names. not sure if necessary.
EDIT 2/18 (1): went back to og, with timestamp, this is because if we type their major for them the title might be too long
Closes #789 

updated addplan modal to support empty plan name

---

packages/api/package.json
packages/api/src/constants.ts
packages/api/src/major/major.service.ts
packages/api/src/major/majors/2021/computer-information-science/computer_science_bacs/parsed.commit.json
packages/common/src/constants.ts
packages/common/src/major2-validation.ts
packages/common/src/utils.ts
packages/common/test/major2-validation.test.ts
packages/frontend/components/Plan/AddPlanModal.tsx
packages/frontend/components/Plan/EditPlanModal.tsx
packages/frontend/components/Plan/ErrorModalError.tsx
packages/frontend/components/Plan/Plan.tsx
packages/frontend/components/Plan/ReqErrorModal.tsx
packages/frontend/components/Plan/ScheduleTerm.tsx
packages/frontend/components/Plan/index.ts
packages/frontend/components/ScheduleCourse/ScheduleCourse.tsx
packages/frontend/components/Sidebar/ConcentrationDropdownWarning.tsx
packages/frontend/components/Sidebar/Sidebar.tsx
packages/frontend/components/Sidebar/SidebarContainer.tsx
packages/frontend/utils/constants.ts
yarn.lock

For all majors that have concentrations, you can now select undecided as an option.
Frontend changes to add undecided as an option when selecting concentrations as well as displaying warning dropdowns letting you know that the concentration is undecided and will eventually need changing. Also some backend validation changes that allow an undecided concentration to exist even though it's not defined anywhere in the major. 
Closes #790 
Visually

790 allow plans with no concentration

---

packages/api/ormconfig.ts

Changing path in ormconfig.ts to *hopefully* fix the SSL issues we've been getting. This file is already in /api so should be able to just access the cert through /assets/path_to_cert

edited ssl path

---

packages/api/src/main.ts
packages/api/src/major/major-collator.ts

Removed interceptor for main api. This makes it so that it doesn't log every single major json file when we make the api call! Might be worth looking into again so we log actually important information.

no more logging entire json files

---

packages/api/src/major/major-collator.ts

Removing console logs from the collator so linting warnings are removed from console when we run backend tests. To run backend tests:
cd packages
cd api
yarn jest OR yarn test
All tests should pass

clean console when running backend tests

---

packages/api/src/interceptors/logging.interceptor.ts
packages/api/src/main.ts

hides the body of responses that have to do with /major and /minor because they take up the entire terminal space and dont help

Logging cleanup

---

packages/api-client/index.ts
packages/api/migrations/1757878658490-ReplaceMinorWithMinorsArray.ts
packages/api/src/plan/entities/plan.entity.ts
packages/api/src/plan/plan.service.ts
packages/api/src/student/entities/student.entity.ts
packages/common/src/api-dtos.ts
packages/common/src/api-response-types.ts
packages/frontend/components/Plan/AddPlanModal.tsx
packages/frontend/components/Plan/EditPlanModal.tsx
packages/frontend/components/Sidebar/Sidebar.tsx
packages/frontend/hooks/useMajor.ts
packages/frontend/hooks/useMinor.ts

Ticket containing the migration of minor: string to minors: string[] so a plan can have multiple minors. All schema files changed so there are no errors and the app can run normally with no errors in the console. Updated the edit and add plan modal to allow plans to be made with a combination of multiple majors and minors. 
The sidebar still is only showing the first major and minor in the plan, but the others are there we are just awaiting a design for the best way to showcase them.
Closes # (861)
This has migration changes and will eventually require a run of `yarn dev:migration:run` ONCE we merge the entirety of flexible-majors in.

Flexible minors
