sandboxnu/graduatenu

html_parser.js

Moved logic for different parts of the degree audit into individual functions.
Fixed the logic for producing the courses that are required.
To test:
Run the code as per the README of this repository.
Ensure that the degree audit produced is as desired.

fix-parser

---

html_parser.js

Reverts sandboxneu/scheduleneu#9

Revert "fix-parser"

---

.github/workflows/main.yml
src/json_parser.js

Added Actions.
Runs tests on push.
$ yarn
$ yarn test
Feel free to add more stuff before merging!

GitHub actions ci

---

.prettierrc
package.json
src/html_parser.ts
src/json_converter.ts
src/json_loader.ts
src/json_parser.ts
src/types.ts
test/html_parser.test.js
test/json_parser.test.js
yarn.lock

This should keep our styling options the same between us. Make sure to install and enable the prettier plugin for VScode for this to take effect.
No content in the files was changed, just the formatting.

added prettier.rc and formatted all files

---

backend/test/warnings.test.js

Tests were failing due to incorrect filepaths.

Fixed failing tests

---

.gitignore
.nowignore
now.json

Using [Zeit Now](https://zeit.co)

auto deploy frontend folder

---

frontend/src/App.tsx
frontend/src/components/DropDownModal.tsx

Reverts sandboxnu/graduatenu#57

Add "Completed Courses" modal"

---

backend/test/prereq_loader.test.js
package.json

Real fix test

---

frontend/src/api/index.ts

Fixed the last bug for frontend warnings not working on added courses.

missing prereqs warning bugfix

---

frontend/src/components/Year/Year.tsx
frontend/src/components/Year/YearTop.tsx
frontend/src/constants/index.ts
frontend/src/home/Home.tsx
frontend/src/home/HomeWrapper.tsx

Also, I made it so the toasts auto dismiss.

added year to semester block

---

frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/Year/Year.tsx
frontend/src/state/store.ts
frontend/src/utils/generate-warnings.ts
yarn.lock

This PR fixes the weird mutation bug from the redux PR (#78).

Fix redux mutation

---

frontend/src/components/SemesterBlock.tsx
frontend/src/state/actions/scheduleActions.ts
frontend/src/state/index.ts
frontend/src/state/reducers/scheduleReducer.ts
yarn.lock

Note: This PR is not meant to be merged until the redux PR is merged.

Adding undo button upon deletion of a class

---

frontend/package.json
frontend/public/index.html
frontend/src/Onboarding/Onboarding.tsx
package.json

Changed the name of the website and made some minor adjustments to the wording of the landing page.
To test:
Look at the deployment and make sure that it reflects the naming changes made in the code.

Naming changes

---

frontend/src/utils/generate-warnings.ts

Made sure that duplicate classes that are filler classes are not marked as duplicates

Fixed the bug for duplicates on filler classes

---

frontend/src/models/types.ts
scrapers/src/catalog-scraper/catalog_scraper.ts
scrapers/src/catalog-scraper/reqGroup_scraper.ts
scrapers/src/catalog-scraper/row_scraper.ts
scrapers/src/catalog-scraper/subHeader_scraper.ts
scrapers/src/utils/scraper_utils.ts
scrapers/test/__snapshots__/catalog_scraper.test.js.snap
scrapers/test/catalog_scraper.test.js

Several changes to the catalog scraper, such as modifying the way it parses or courses, changing the way Ranges are parsed to allow rows that have no course links on it and adding in an end range, allowing for ranges specified by 'any ____ course' type of rows, making some small alterations to subheader parsing and some other smaller bugs. 
Also added several new majors.

Catalog scraper tests

---

frontend/src/components/ClassBlocks/ClassBlock.tsx
frontend/src/components/SemesterBlock.tsx
frontend/src/components/Sidebar/RequirementSection.tsx
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/Sidebar/SidebarClassBlock.tsx
frontend/src/home/Home.tsx
frontend/src/home/Scrollbar.css

Some miscellaneous improvements for the home page:
- Fix weird homepage scaling bug on master
- Fix class blocks not displaying warning colors
- Complex sidebar requirement group rendering with indentations
- Sidebar scroll independent from schedule scroll

Home page fixes

---

frontend/src/components/ClassBlocks/ClassBlock.tsx
frontend/src/components/SemesterBlock.tsx

Added multi line warning tooltip and moved warning tooltip below the ClassBlock.

Render ClassBlock with multiple warnings

---

api/db/schema.rb
frontend/src/components/SemesterBlock.tsx
frontend/src/components/Sidebar/SidebarAddClassModal.tsx
frontend/src/state/reducers/scheduleReducer.ts
frontend/src/utils/dnd-helpers.ts
frontend/src/utils/generate-warnings.ts
scrapers/test/warnings.test.js

pull request for classes during coop

Classes during coop

---

frontend/Dockerfile
frontend/package.json
package.json
yarn.lock

Broke the deploy again and fixed it.

fix deploy

---

common/tests/__snapshots__/prereq_loader.test.js.snap

Due to the new semester on banner and some modified prereqs, some of our tests were failing. 
I validated that all of the changes were correct with the prereqs listed on banner and updated them.

Fix Failing Prereq Loader Tests

---

frontend/src/Onboarding/Onboarding.tsx

Changing the hover on the welcome button to be grey instead of red

Fix Welcome Button Hover

---

api/Gemfile
api/Gemfile.lock
api/app/models/plan.rb
api/app/models/user.rb
api/db/schema.rb
api/lib/tasks/auto_annotate_models.rake
api/test/fixtures/plans.yml
api/test/fixtures/users.yml
api/test/models/plan_test.rb
api/test/models/user_test.rb

This is so it's a lot easier to know which fields are on each model

add annotate gem and annotate models

---

frontend/src/state/reducers/scheduleReducer.ts

Small bug fix to ensure toggling the closed year allows it to open (currently could only close)

Open Closed Year Bug

---

api/app/models/plan.rb
api/lib/tasks/seed_db.rake
api/test/fixtures/plans.yml
api/test/models/plan_test.rb

To use:
Make sure database is migrated to latest
And run `docker-compose run server rake seed_users`
Or if you're running rails locally: `rake seed_users`
Do delete all users do
`docker-compose run server rails c`
and then
`User.destroy_all`

add script to fill db with 100 users

---

api/app/models/user.rb
api/db/schema.rb
api/test/fixtures/users.yml
api/test/models/user_test.rb
frontend/src/Onboarding/RedirectScreen.tsx

The copy can be changed to whatever.

Add loading indicator to login

---

frontend/src/home/EditPlanPopper.tsx
frontend/src/profile/Profile.tsx
frontend/src/state/reducers/userReducer.ts

Edit grad year in profile screen

---

frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/home/Home.tsx

Move sidebar to left of screen

---

frontend/src/Onboarding/TransferableCreditScreen.tsx
frontend/src/home/AddPlanPopper.tsx
frontend/src/home/EditPlanPopper.tsx
frontend/src/state/actions/userPlansActions.ts
frontend/src/state/reducers/userPlansReducer.ts
frontend/src/utils/schedule-helpers.ts

- Have years show up correctly (based off their academic year and graduation year)
- Consider given coop cycle (number of years and the appropriate semesters are marked as COOP)

overhaul initial schedule generation

---

frontend/src/home/AddPlanPopper.tsx
frontend/src/home/EditPlanButton.tsx

See trello card for acceptance criteria

add plan popper improvements

---

.github/workflows/aws-cd.yml

We almost out of the free tier 😬

stop pushing to aws ecs on merge to master

---

frontend/src/advising/ManageStudents/ExpandedStudentView.tsx

This works surprisingly well for now, we might want to update the styling in the future.

add sidebar for edit student schedule screen

---

api/app/controllers/users_controller.rb
common/tests/__snapshots__/prereq_loader.test.js.snap

Encrypting email and nuid broke search. Fixed it by removing raw SQL.

fix broken search

---

common/tests/__snapshots__/prereq_loader.test.js.snap
frontend/src/utils/schedule-helpers.ts

- Updating year bug that prevents deleting a course from fall semesters
- Updating the starting year so that the year for a semester/year is the ending year for that academic year

Year Fixes

---

frontend/src/utils/flattenRequirements.ts
frontend/src/utils/generate-warnings.ts
frontend/src/utils/requirementGroupUtils.ts

The new `ICreditRangeCourse` needs to be included for validation within the sidebar. 
Adds a new method `processICreditRangeCourse` for generating warnings for this type of requirement.

Add validation for ICreditRangeCourse

---

frontend/src/Onboarding/GenericOnboarding.tsx
frontend/src/Onboarding/OnboardingInfoScreen.tsx
frontend/src/components/common/DisclaimerPopup.tsx

Adding disclaimer text to the OnboardingInfo Screen

Disclaimer Text

---

frontend/src/advising/Templates/TemplateBuilderPage.tsx
frontend/src/state/actions/userPlansActions.ts
frontend/src/state/index.ts
frontend/src/state/reducers/userPlansReducer.ts

In template builder, advisor can edit plan name
https://trello.com/c/4lOn9Aj8/312-allow-advisors-to-edit-their-plan-names

Edit plan name from advisor end

---

frontend/src/home/RequestFeedbackPopper.tsx

We want students to schedule an appointment with their advisor when they request for feedback. (Requested by advisors)

Update ui for requesting feedback

---

frontend/src/components/SemesterBlock.tsx

https://trello.com/c/MExkacJH
removed add button for vacation terms

removed add button for vacation terms

---

frontend/src/components/SemesterBlock.tsx
infrastructure/deploy/redeploy.sh

We renamed the master branch to main so need to rename it in the redeploy script too :)

Rename master to main in redeploy.sh

---

common/ap_exams.ts
frontend/src/components/TransferCreditHolder.tsx

Added on-hover text for transfer courses!

Transfer course hover text

---

common/types.ts

Implemented new Major2 type :)

Add new major types

---

frontend/src/Onboarding/Onboarding.tsx

Make a change to test staging CD

---

frontend/package.json
frontend/src/App.tsx
frontend/src/error/ErrorHandler.tsx
frontend/src/error/ErrorPages.tsx
frontend/src/error/GenericErrorPage.tsx
yarn.lock

Refactor `ErrorPage` to `GenericErrorPage`, `FrontendErrorPage`, and `BackendErrorPage` for components for error catching.
Feature
Broke the frontend code and saw the error page pop up :') see gif ^
*Note: actual error pops up in dev mode on chrome, can be closed by hitting X or ESC, would not show up in prod

Frontend react error handling

---

frontend/src/Onboarding/RedirectScreen.tsx
frontend/src/components/Routes/ProtectedRoute.tsx
frontend/src/utils/auth-helpers.ts

Previously, the app would error if vising `/home` when the user is not logged in, and also frequently during development with error `TypeError: getStudentFromState(...) is not defined`. This change fixes both bugs.
Tested manually:
1. while logged out, visit `/home` redirects to `/`
2. during development, while in progress during onboarding flow, make a code change and cause app to hot reload. app no longer crashes.

fix getStudentFromState is not defined, clean up RedirectScreen

---

frontend/src/Onboarding/CompletedCoursesScreen.tsx
frontend/src/Onboarding/GenericOnboarding.tsx
frontend/src/Onboarding/LoginScreen.tsx
frontend/src/Onboarding/OnboardingInfoScreen.tsx
frontend/src/Onboarding/TransferCoursesScreen.tsx
frontend/src/Onboarding/TransferableCreditScreen.tsx
frontend/src/advising/ManageStudents/StudentView.tsx
frontend/src/advising/Templates/TemplateBuilderPage.tsx
frontend/src/components/AddClassSearchModal.tsx
frontend/src/components/ClassBlocks/ClassBlockBody.tsx
frontend/src/components/ClassBlocks/LargeClassBlock.tsx
frontend/src/components/ClassBlocks/SmallClassBlock.tsx
frontend/src/components/Semester/SemesterBlock.tsx
frontend/src/components/Sidebar/RequirementSection.tsx
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/TransferCreditHolder.tsx
frontend/src/components/UndoDelete.tsx
frontend/src/home/EditPlanPopper.tsx
frontend/src/state/actions/studentActions.ts
frontend/src/state/reducers/studentReducer.ts
frontend/src/state/reducers/userPlansReducer.ts
frontend/src/utils/completed-courses-helpers.ts
frontend/src/utils/course-helpers.ts
frontend/src/utils/generate-warnings.ts
frontend/src/utils/schedule-helpers.ts
scrapers/src/json_converter.ts

(if gif is not working, please ctrl+click to open in new tab)
Fixes a bug where transfer courses added during onboarding weren't correctly being added to the schedule as transfer courses. More specifically, fixes:
1. slowdown due to consecutive awaits for fetching courses (fix is to use Promise.all)
2. incorrect course equality checks
3. double-equals equality checks
Additionally, this cleans up some missing-key warnings, deduplicates some code,
and also adds text for the steps displayed during onboarding.
Tested locally by selecting completed courses in the onboarding workflow and checking that they show up in transfer credit holder.
I have not written any tests for my code.
1. Should we change the strategy used to add …

fix completed courses bug

---

packages/api-client/index.ts
packages/frontend-v2/pages/index.tsx

Merged useSWR custom hooks with type errors. This PR fixes these type errors.
Reran all tests for useSWR custom hooks PR #420.

Fix typing errors

---

.gitignore
packages/common/test/assets/postman-api.json

This PR adds postman api json to test assets since we can no longer share for free. In the future, if we update anything in backend, we can just change the json directly. But of course, we might want to add API tests soon.
Additionally, it also adjusts gitignore. `*.json` only has effect on `package-lock.json` so I just added that one in specifically. I think we might also want to commit other json files too in the future.
Provide instructions so we can reproduce. 
Test in postman

Add Postman API JSON

---

.github/workflows/aws-cd.yml

CD fails since i didn't comment out the entire file. Probably a better way to do this but this works.

Rollback CD properly by commenting it all out

---

packages/scrapers-v2/test/__snapshots__/urls.test.ts.snap

Northeastern added the following major:
Environmental and Sustainability Sciences and Journalism, BS
This PR just adds a newly added major to the Jest snapshot for the scraper.

Tests - Update Scraper Tests with New Major

---

packages/common/src/major2-validation.ts
packages/common/src/types.ts
packages/common/test/major2-validation.test.ts

Updated the major validation algorithm to schedule2 type
Closes # 455
We ran the yarn test in the common folder.

Validation schedule2 type

---

packages/api-v2/src/plan/entities/plan.entity.ts
packages/common/src/api-dtos.ts
packages/common/src/api-response-types.ts
packages/frontend-v2/components/AddCourseModal/AddCourseModal.tsx
packages/frontend-v2/components/AddCourseModal/SearchResult.tsx
packages/frontend-v2/components/AddCourseModal/SelectedCourse.tsx
packages/frontend-v2/components/Button/BlueButton.tsx
packages/frontend-v2/components/Button/index.ts
packages/frontend-v2/components/Error/ErrorBoundary.tsx
packages/frontend-v2/components/Plan/AddPlanModal.tsx
packages/frontend-v2/components/Plan/Plan.tsx
packages/frontend-v2/components/Plan/PlanDropdown.tsx
packages/frontend-v2/components/Plan/ScheduleTerm.tsx
packages/frontend-v2/components/Plan/index.ts
packages/frontend-v2/components/index.ts
packages/frontend-v2/hooks/useStudentWithPlans.ts
packages/frontend-v2/pages/home.tsx
packages/frontend-v2/utils/index.ts
packages/frontend-v2/utils/plan/createEmptySchedule.ts
packages/frontend-v2/utils/plan/index.ts
packages/frontend-v2/utils/theme/components/buttons.ts

We can now create a new plan.
Callouts
- The UX for this feature isn't finalized so I just made it look decent for now. 
- We also don't have majors/concentrations/catalog year data scraped yet so going off of some mock data for now. 
- This stuff is mostly used for requirements validation so we'll fix it when we implement that.
Other changes
- Remove the coop cycle field from a Plan
- Fix all imports from utility files to import from utils directory 
Closes https://github.com/sandboxnu/graduatenu/projects/1#card-85686954
Manually tested by adding a new plan and playing around with it.
- [x I have performed a self-review of my own code

Frontend V2 - Adding A New Plan

---

packages/frontend-v2/components/Button/GrayButton.tsx
packages/frontend-v2/components/Button/index.ts
packages/frontend-v2/components/Plan/DeletePlanModal.tsx
packages/frontend-v2/components/Plan/index.ts
packages/frontend-v2/pages/home.tsx

https://user-images.githubusercontent.com/30478978/195732696-d04f0c89-79ef-40c7-a1d8-91ef6dcb2b03.mov
Support to delete a plan. UX is jank and ad-hoc, will go in an update it once designers finalize the UX for the feature.
Closes #453
Manually, see video.

Add support for deleting a plan

---

packages/common/src/types.ts
packages/frontend-v2/utils/course/getCourseCoreqs.ts
packages/frontend-v2/utils/plan/preAndCoReqCheck.ts

Simply just updates a type name in common, as well as everywhere else it is used.

Update type name I missed oops

---

packages/common/src/types.ts
packages/frontend-v2/components/Plan/ScheduleTerm.tsx
packages/frontend-v2/components/Plan/ScheduleYear.tsx
packages/frontend-v2/utils/plan/addClassesToTerm.ts
packages/frontend-v2/utils/plan/createEmptySchedule.ts
packages/frontend-v2/utils/plan/findTerm.ts
packages/frontend-v2/utils/plan/preparePlanForDnd.ts
packages/frontend-v2/utils/plan/removeCourseFromTerm.ts
packages/frontend-v2/utils/plan/removeYearFromPlan.ts
packages/frontend-v2/utils/plan/updatePlanOnDragEnd.ts

Removed all uses of year from Term and replaced them all with schedule.year in various different ways.
Closes #494 
Manually tested and the regular tests also work.
Manual test: Create a new plan, add and delete years and make sure the years are consistent. Also made sure drag and drop worked

Nick remove year

---

infrastructure/prod/entrypoint.server.sh

They aren't working in prod, simply disabling them for now till I find the fix.
Deployed fix to staging to test.

Stop running migrations in prod

---

packages/api-client/index.ts
packages/api-v2/src/plan/plan.controller.ts
packages/api-v2/src/student/student.controller.ts
packages/common/src/api-response-types.ts
packages/frontend-v2/components/Error/ConfirmEmailWarningModal.tsx
packages/frontend-v2/components/Error/index.ts
packages/frontend-v2/hooks/useLocalStorage.ts
packages/frontend-v2/pages/confirmEmail.tsx
packages/frontend-v2/pages/emailConfirmation.tsx
packages/frontend-v2/pages/home.tsx
packages/frontend-v2/pages/signup.tsx

Instead of forcing the user to confirm their email, we now allow the user to bypass this and use the homepage regardless of if they have confirmed their email.
Closes #564 
Ran through workflows
https://user-images.githubusercontent.com/20124104/224527230-cd20d56f-18d2-4a43-a55c-41c51ff26c4d.mov

Optional Email Confirmation

---

packages/api-v2/.env.development
packages/frontend-v2/components/Header/AccountOverview.tsx

Does 2 things:
- Remove email credentials
- Remove unneeded attribute in `Account Overview`

I forgot to do stuff in my previous PR

---

packages/api-v2/src/major/majors/Computer_Science_BACS/Computer_Science_BACS-2021.json
packages/api-v2/src/major/majors/Computer_Science_BACS/Computer_Science_BACS-2022.json
packages/api-v2/src/major/majors/Computer_Science_BSCS/Computer_Science_BSCS-2021.json
packages/api-v2/src/major/majors/Computer_Science_BSCS/Computer_Science_BSCS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_English_BS/Computer_Science_and_English_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_English_BS/Computer_Science_and_English_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Mathematics_BS/Computer_Science_and_Mathematics_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Mathematics_BS/Computer_Science_and_Mathematics_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Physics_BS/Computer_Science_and_Physics_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Physics_BS/Computer_Science_and_Physics_BS-2022.json

This is a Major Review PR, which contains the following parsed majors. Please check them against the course catalog for accuracy and make necessary corrections. When you're working on a major, make sure to check the started/finished boxes as necessary so we don't accidentally duplicate work. 
**Started:**
**Finished:**

[Major Review] Group 1 (Computer Science+)

---

packages/api-v2/src/major/majors/Computer_Science_and_Design_BS/Computer_Science_and_Design_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Design_BS/Computer_Science_and_Design_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Economics_BS/Computer_Science_and_Economics_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Economics_BS/Computer_Science_and_Economics_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Game_Development_BS/Computer_Science_and_Game_Development_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Game_Development_BS/Computer_Science_and_Game_Development_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_History_BS/Computer_Science_and_History_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_History_BS/Computer_Science_and_History_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Journalism_BS/Computer_Science_and_Journalism_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Journalism_BS/Computer_Science_and_Journalism_BS-2022.json

This is a Major Review PR, which contains the following parsed majors. Please check them against the course catalog for accuracy and make necessary corrections. When you're working on a major, make sure to check the started/finished boxes as necessary so we don't accidentally duplicate work.
**Started:**
**Finished:**

[Major Review] Group 6 (Computer Science+++)

---

packages/api-v2/src/major/majors/Data_Science_and_Ecology_and_Evolutionary_Biology_BS/Data_Science_and_Ecology_and_Evolutionary_Biology_BS-2021.json
packages/api-v2/src/major/majors/Data_Science_and_Ecology_and_Evolutionary_Biology_BS/Data_Science_and_Ecology_and_Evolutionary_Biology_BS-2022.json
packages/api-v2/src/major/majors/Data_Science_and_Economics_BS/Data_Science_and_Economics_BS-2021.json
packages/api-v2/src/major/majors/Data_Science_and_Economics_BS/Data_Science_and_Economics_BS-2022.json
packages/api-v2/src/major/majors/Data_Science_and_Health_Science_BS/Data_Science_and_Health_Science_BS-2021.json
packages/api-v2/src/major/majors/Data_Science_and_Health_Science_BS/Data_Science_and_Health_Science_BS-2022.json
packages/api-v2/src/major/majors/Data_Science_and_Mathematics_BS/Data_Science_and_Mathematics_BS-2021.json
packages/api-v2/src/major/majors/Data_Science_and_Mathematics_BS/Data_Science_and_Mathematics_BS-2022.json
packages/api-v2/src/major/majors/Data_Science_and_Physics_BS/Data_Science_and_Physics_BS-2021.json
packages/api-v2/src/major/majors/Data_Science_and_Physics_BS/Data_Science_and_Physics_BS-2022.json
packages/api-v2/src/major/majors/Data_Science_and_Psychology_BS/Data_Science_and_Psychology_BS-2021.json
packages/api-v2/src/major/majors/Data_Science_and_Psychology_BS/Data_Science_and_Psychology_BS-2022.json

This is a Major Review PR, which contains the following parsed majors. Please check them against the course catalog for accuracy and make necessary corrections. When you're working on a major, make sure to check the started/finished boxes as necessary so we don't accidentally duplicate work.
**Started:**
**Finished:**

[Major Review] Group 3 (Data Science++)

---

packages/api-v2/src/major/majors/Computer_Science_and_Behavioral_Neuroscience_BS/Computer_Science_and_Behavioral_Neuroscience_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Behavioral_Neuroscience_BS/Computer_Science_and_Behavioral_Neuroscience_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Biology_BS/Computer_Science_and_Biology_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Biology_BS/Computer_Science_and_Biology_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Cognitive_Psychology_BS/Computer_Science_and_Cognitive_Psychology_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Cognitive_Psychology_BS/Computer_Science_and_Cognitive_Psychology_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Communication_Studies_BS/Computer_Science_and_Communication_Studies_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Communication_Studies_BS/Computer_Science_and_Communication_Studies_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Criminal_Justice_BS/Computer_Science_and_Criminal_Justice_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Criminal_Justice_BS/Computer_Science_and_Criminal_Justice_BS-2022.json

This is a Major Review PR, which contains the following parsed majors. Please check them against the course catalog for accuracy and make necessary corrections. When you're working on a major, make sure to check the started/finished boxes as necessary so we don't accidentally duplicate work.
**Started:**
**Finished:**

[Major Review] Group 5 (Computer Science++)

---

packages/api-v2/src/major/majors/Computer_Science_and_Linguistics_BS/Computer_Science_and_Linguistics_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Linguistics_BS/Computer_Science_and_Linguistics_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Media_Arts_BS/Computer_Science_and_Media_Arts_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Media_Arts_BS/Computer_Science_and_Media_Arts_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Philosophy_BS/Computer_Science_and_Philosophy_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Philosophy_BS/Computer_Science_and_Philosophy_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Sociology_BS/Computer_Science_and_Sociology_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Sociology_BS/Computer_Science_and_Sociology_BS-2022.json
packages/api-v2/src/major/majors/Computer_Science_and_Theatre_BS/Computer_Science_and_Theatre_BS-2021.json
packages/api-v2/src/major/majors/Computer_Science_and_Theatre_BS/Computer_Science_and_Theatre_BS-2022.json

This is a Major Review PR, which contains the following parsed majors. Please check them against the course catalog for accuracy and make necessary corrections. When you're working on a major, make sure to check the started/finished boxes as necessary so we don't accidentally duplicate work.
**Started:**
**Finished:**

[Major Review] Group 7 (Computer Science++++)

---

.github/PULL_REQUEST_TEMPLATE
README.md

Super simple change that just updates our readme to include creating `.env` file for testing, and update the PR template slightly.

Update PR template and README

---

packages/common/test/assets/postman-api.json

Updates Postman API template. More specifically, updates the `createPlan` POST route.
To test this, download the template and ensure that all routes are working as expected.

Update postman create-plan to work with new BE requirements

---

package.json

Easy change to add husky back for prettier. FINALLY BEAUTIFUL FORMATTING!
Just make sure we all run `yarn` before your next commit/push.

Add husky prettier for 

---

packages/frontend-v2/components/Sidebar/SectionRequirement.tsx
packages/frontend-v2/components/Sidebar/SidebarSection.tsx

Decreased some font sizes in the sidebar. The previous 16px was a bit big for body text.
Before:
After:

Decrease sidebar font size

---

packages/frontend-v2/components/AddCourseModal/AddCourseButton.tsx

Renamed the "Add Course" button to "Add Courses" to be more accurate and consistent with the modal

Add Course -> Add Courses

---

packages/api-v2/src/main.ts

We currently log a lot of junk in production. This PR varies logger log levels based on the environment (``development`` or ``production``).
Closes [#6](https://github.com/sandboxnu/major-scraper/issues/6).

feat: vary logging based on env

---

packages/frontend-v2/components/Sidebar/SectionRequirement.tsx

Standardize requirement rendering

---

packages/frontend-v2/components/Header/ChangePassword.tsx
packages/frontend-v2/components/Header/GraduateHeaders.tsx
packages/frontend-v2/components/Header/UserDropdown.tsx
packages/frontend-v2/components/Plan/DeletePlanModal.tsx
packages/frontend-v2/components/Sidebar/Sidebar.tsx
packages/frontend-v2/pages/index.tsx
packages/frontend-v2/pages/login.tsx
packages/frontend-v2/pages/signup.tsx

Updated various lines of text according to [this Figma section](https://www.figma.com/file/yUflVFVxjMynm7gGymLpQY/%F0%9F%8F%97-Current-Work?type=design&node-id=5043%3A1986&mode=design&t=bWJDm0nH8qkNLcV9-1)

Text Fixes

---

.github/workflows/aws-cd.yml

I'm pretty sure the current build issue is because I accidentally left the quotes escaped in the build args.

Fix AWS-CD Script

---

packages/frontend-v2/components/AddCourseModal/AddCourseButton.tsx
packages/frontend-v2/components/Authentication/AuthForm.tsx
packages/frontend-v2/components/Button/SecondaryBlueButton.tsx
packages/frontend-v2/components/Error/ConfirmEmailWarningModal.tsx
packages/frontend-v2/components/Plan/AddPlanModal.tsx
packages/frontend-v2/components/Plan/DeletePlanModal.tsx
packages/frontend-v2/components/Plan/EditPlanModal.tsx
packages/frontend-v2/components/Plan/TransferCourses.tsx
packages/frontend-v2/hooks/useLocalStorage.ts
packages/frontend-v2/hooks/useRedirectIfLoggedIn.ts
packages/frontend-v2/hooks/useStudentWithPlans.ts
packages/frontend-v2/pages/_app.tsx
packages/frontend-v2/pages/home.tsx
packages/frontend-v2/pages/login.tsx
packages/frontend-v2/pages/signup.tsx
packages/frontend-v2/utils/constants.ts

This PR adds support for sign in as guest.
Closes #675 
https://github.com/sandboxnu/graduatenu/assets/20124104/bab7e7f9-2c26-4cd9-bd6d-5f68a777c5b3
Ran through all use cases and ensured that all previous features are still working
**NOTE**:
- When logging in as a guest, there will be a toast warning that informs the user that data will not be saved. When running the application in a developer environment (e.g not prod or staging), the warning toast will appear twice. This is because react runs all `useEffects` twice to ensure that developers are using the `useEffect` correctly. To test that the toast only appears once, build the FE docker image and run that as stipulated in the Readme.

Signin as guest

---

package.json
packages/common/src/utils.ts
packages/frontend/components/Form/Select.tsx
packages/frontend/components/Plan/AddPlanModal.tsx
packages/frontend/utils/plan/supportedMajors.ts
yarn.lock

We added fuzzy search filter to the Select component to fix the issue of "Computer Science, BSCS" sorting. We also added a comparator to sort the supported major list.
Closes #663
https://github.com/sandboxnu/graduatenu/assets/57577392/a38e0c23-f1d6-446f-9604-08fd4c8adb05

Add Fuzzy Search in Drop Down 

---

packages/frontend/components/Plan/AddPlanModal.tsx
packages/frontend/components/Plan/EditPlanModal.tsx

Fixed placeholder attribute from #704

---

packages/frontend/components/AddCourseModal/AddCourseModal.tsx

Resets the NUPaths in the add course modal when its closed/open
Closes #716 
https://github.com/sandboxnu/graduatenu/assets/20124104/e8dfb974-1099-43c9-8ee9-7f6dea0c57b9

Reset selected NUPATHS when closing the modal

---

packages/frontend/components/AddCourseModal/NUPathLabel.tsx

I made the tags a bit too small in the UI tweak
New:

Make nupath tags bigger

---

packages/frontend/components/Header/GraduateHeaders.tsx

Updated the feedback form links
Closes #723 

Update Feedback Google Form Links

---

packages/api/src/major/major.service.ts
packages/common/src/api-dtos.ts
packages/common/src/types.ts
packages/common/src/utils.ts
packages/frontend/components/Form/Select.tsx
packages/frontend/components/Plan/AddPlanModal.tsx
packages/frontend/components/Plan/EditPlanModal.tsx
packages/frontend/components/Sidebar/Sidebar.tsx
packages/frontend/utils/constants.ts
packages/frontend/utils/plan/supportedMajors.ts

Implement major metadata for check for verified majors
- update supportedMajors endpoint to add verified key 
- update select component to have different label and value for adding beta marking on major names 
- adding badge for beta major on sidebar 
- add checkbox for agreeing to use beta major 
Closes #666

Beta major support

---

packages/api-client/index.ts
packages/api/src/main.ts
packages/frontend/next.config.js
packages/frontend/package.json
yarn.lock

Code to complete the Vercel migration using a branch-based deployment strategy. This'll require some extra changes on the config side + a backend prod deploy once merged.
Big shoutout to Christina and Luke Jianu who led investigation for this last semester.
Tested on Vercel using this branch.

Vercel Migration

---

packages/frontend/components/Plan/AddPlanModal.tsx
packages/frontend/components/Plan/EditPlanModal.tsx

Fixes issue where creating a no major plan was disabled
- x ] Bug fix (non-breaking change which fixes an issue)

change condition for disabling button

---

packages/frontend/components/Sidebar/Sidebar.tsx

Remove no major ugly background 

---

packages/frontend/components/Form/Select.tsx
packages/frontend/components/Plan/AddPlanModal.tsx
packages/frontend/components/Plan/EditPlanModal.tsx

Fix bug where fuzzy search wasn't working
https://github.com/sandboxnu/graduatenu/assets/20124104/4401ce7c-f1ad-493d-8abc-bb35847cb384

Fix Fuzzy Search

---

packages/frontend/components/Plan/AddPlanModal.tsx

Update the color of the checkbox stroke for the consistent darker blue

[DESIGN-FIX] Update the Checkbox in the AddPlanModal for stroke consistency

---

packages/frontend/components/AddCourseModal/SearchResult.tsx

Wrapping the SearchNEU button in a tooltip so there is a hovering hint indicating what the button is 
Update for #750 

adding tooltip for searchneu button

---

packages/api/src/major/majors/2023/computer-information-science/Computer_Science_and_Game_Development_BS/parsed.initial.json
packages/frontend/utils/plan/getAllCoursesInMajor.ts

Closes #760
Fixed bug that had CS and Game Development major from crashing by creating a helper function that handled nested arrays

Course crash bug

---

packages/frontend/components/Plan/TransferCourses.tsx

Update "Transfer Course" text to "Overriden Course" to match design
Closes #775 

Update Transfer Course Text to Overriden Course Text

---

packages/common/src/major2-validation.ts
packages/common/test/major2-validation.test.ts

In the major validator, we have a set of courses that include all the REQUIRED courses that SHOULD NOT be considered in the range validator. This fixed the infinite loading sidebar validators. I dont think this is optimal and would be inefficient because we are fetching and grabbing the required courses every time we want to validate. 
Closes #794 
Tested changes with debug statements to check what courses are excluded and which ones are being considered.

Range update (fixed infinite loading)

---

packages/api/major-scanner.ts

Implement a script that goes through the major requirements JSON and produces a list of majors that have the following issues:
- concentrations have names like "Electives" or "General Requirements" meaning the concentrations were improperly scraped 
- there is a structure error to requirements (ex. the requirement has a nested array of requirements)
Produces the following logs:
[major-scanner.log](https://github.com/user-attachments/files/18850655/major-scanner.log)
Closes #809 

Major Structure Scanner 

---

README.md
package.json

Added a script `yarn wdev` to run the development script for windows machines.

added wdev script for windows

---

package.json
packages/frontend/pages/_app.tsx
yarn.lock

Adding vercel analytics. Ready to merge if approved by Kobe. 
https://vercel.com/docs/analytics
It will be useful to find visitor and page view statistics.

Setting up vercel analytics

---

packages/api/src/major/majors/2024/computer-information-science/computer_science_bacs/parsed.initial.json
packages/api/src/major/majors/2024/computer-information-science/computer_science_bscs/parsed.initial.json

There is an issue with the Software Concentration parsing of 2024 BSCS and BACS.

updating software concentration of CS 2024

---

.github/workflows/main.yml
infrastructure/prod/redeploy.sh

removing frontend workflow and deploy to node on AWS

---

packages/common/src/types.ts
packages/frontend/components/Icon/GreenCheckIcon.tsx
packages/frontend/components/Plan/Plan.tsx
packages/frontend/components/Plan/ReqErrorModal.tsx
packages/frontend/hooks/useMutateStudentWithPlan.ts
packages/frontend/hooks/useSelectedCourses.ts
packages/frontend/utils/plan/addClassesToTerm.ts
packages/frontend/utils/plan/preAndCoReqCheck.ts
packages/frontend/utils/plan/shiftYearAndSeason.ts

Added a plus icon to the right of every course in the prereq/coreq error modal. Unfortunately, the design is still the same I don't see a way the design that we proposed would be possible so that might need looked at again if we want to consider changing the design. Might be worth moving to a new ticket.
Closes # 752
Upon Kobe's styling changes new ss looks like:
and appears to behave as expected for more complex cases
1) Drag in Algo in first semester
2) add courses that are needed as prereqs/coreqs

#752 Req Modal Improvements

---

packages/frontend/components/GivingDay/GivingDayAccordion.tsx

update spacing of giving day accordion

---

packages/frontend/components/Sidebar/GenericSection.tsx

changing "Generic Course" to "General Course" 

---

.github/workflows/aws-cd.yml

update aws workflow to remove frontend

---

infrastructure/prod/redeploy.sh

deploy index update

---

packages/frontend/components/GivingDay/GivingDayModal.tsx
packages/frontend/pages/index.tsx
packages/frontend/utils/constants.ts

- autofocus on modal donate button
- render giving day modal on top
- abstract modal design and add constants

Addressing Giving Day Accessibility Feedback

---

packages/frontend/components/GivingDay/GivingDayAccordion.tsx
packages/frontend/utils/constants.ts

update giving day link

---

packages/frontend/components/AddCourseModal/AddCourseModal.tsx
packages/frontend/components/AddCourseModal/DropdownTriangle.tsx
packages/frontend/components/AddCourseModal/SearchResult.tsx
packages/frontend/components/AddCourseModal/SelectedCourse.tsx
packages/frontend/components/AddCourseModal/SelectedCourseCombination.tsx

Created a new map to store selected courses. 
804

Combining tiles clean

---

packages/frontend/pages/index.tsx

Giving Day Modal

---

packages/frontend/components/Sidebar/SidebarContainer.tsx
packages/frontend/pages/index.tsx

remove giving day content

---

packages/frontend/components/AddCourseModal/AddCourseModal.tsx

Combined tiles default to open

---

packages/api/src/major/major-collator.ts
packages/frontend/components/AddCourseModal/AddCourseModal.tsx
packages/frontend/components/Plan/EditPlanModal.tsx
packages/frontend/components/Sidebar/Sidebar.tsx
packages/frontend/utils/plan/createScheduleFromTemplate.ts

Log cleanup

---

packages/frontend/components/Sidebar/Sidebar.tsx

This PR updates Sidebar to revalidate courses when a user changes the minor in their plan. Previously, the sidebar would show all minor requirements as complete upon changing their plan, despite their plan not meeting any of the requirements. This was a one-line fix.
Closes # 876
- [ ✓] Bug fix (non-breaking change which fixes an issue)
- [ ✓] I have run the production builds in docker for the frontend/backend and ensure things run fine. Check README of repo on how to run if not sure.
- [✓ ] I have performed a self-review of my own code
- [✓ ] I have commented my code where needed
- [✓ ] I have made corresponding changes to the …

Added minor to the revalidating process
